# Generated by Django 5.2.4 on 2025-07-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='book_url',
            field=models.FileField(blank=True, null=True, upload_to='libros/'),
        ),
    ]
